### ISSUE TITLE
Potentially incompatible change required to top-level dependency

### ISSUE THREAD

**Issue by purplecones** [jagi/meteor-astronomy-relations#3]
Receive the following error when adding this package

```
meteor add jagi:astronomy-relations
 => Errors while adding packages:

While selecting package versions:
error: Potentially incompatible change required to top-level dependency:
jagi:astronomy 0.12.1, was 1.0.2.
Constraints on package "jagi:astronomy":
* jagi:astronomy@0.10.5 <- jagi:astronomy-relations 0.1.2

To allow potentially incompatible changes to top-level dependencies, you must
pass --allow-incompatible-update on the command line.
```

**Comment by lukejagodzinski** [comment]
You can't use this package right now. I haven't updated it yet to work with Astronomy 1.0. Right now I'm working on the `forms` package and after that I will be working on the `relations` package. Most of the features of the `relations` package can be implemented by hand.

**Comment by purplecones** [comment]
Thanks. What do you recommend in the meantime? Publish Composite?

**Comment by lukejagodzinski** [comment]
If you just want to define relations then you don't need any package. However, if you want to publish multiple cursors I've found publishComposite helpful. However there is a better package for the reactive publications from @peerlibrary `peerlibrary:reactive-publish`.

**Comment by purplecones** [comment]
Thanks, I will check it out. Is there a downside in doing something like this using methods on an AstroClass? 

```
Collection = Astro.Class({
  name: 'Collection',
  collection: Collections,
  fields: {
    ...
  },
  methods: {
    getRelatedDocumentsFromAnotherCollection() {
      return RelatedCollection.find({relatedId: this._id}).fetch();
    }
  }
});
```

**Comment by lukejagodzinski** [comment]
No it's ok to do it in the way you presented. Actually the `relations` package is doing it in the same way.

**Comment by ffxsam** [comment]
@purplecones What an awesome idea! Exactly what I was looking for.
