### ISSUE TITLE
Using Astronomy 1.0 in production with relations module

### ISSUE THREAD

**Issue by kahmali** [jagi/meteor-astronomy-relations#5]
Hi Jagi,

Thanks so much for all the awesome work on Astronomy! I'm really hoping to use Astronomy 1.0+ in production, but my code heavily relies on relations. Any update on your plans to include this in 1.0? I saw you mentioned it in the new docs but I haven't heard much about it.

Thanks, and keep up the great work!

**Comment by AnthonyChiavelli** [comment]
+1

**Comment by lukejagodzinski** [comment]
Ok I've received PR for the relations module to make it work with 1.0. I will review it and merge this week. I will notify you here when it's ready.

**Comment by kahmali** [comment]
Awesome! Thanks for the quick response!

**Comment by lukejagodzinski** [comment]
Ok relations module updated. There is a little change comparing to the version working with Astronomy 0.12.x. Please read Astronomy [documentation](http://astronomy.jagi.io/) first.

**Comment by AnthonyChiavelli** [comment]
Thanks so much, Jagi!
